### ISSUE TITLE
Не удается скомпилоровать проект.

### ISSUE THREAD

**Issue by Stinger1000** [GOOD-Stuff/ssw_lab_4sem#11]
Использовал CLion и MinGW, кодировка вроде верна, но все равно ругается на generator.h В чем тогда может быть причина?
![350634-INNERRESIZED600-600-i7Z7J39LW](https://user-images.githubusercontent.com/56435313/75096879-12bc6700-55b5-11ea-9034-dc618d81d21d.jpg)

**Comment by GOOD-Stuff** [comment]
А на что именно он ругается? CMakeLists.txt находится в той же директории, что и исходники? 
Попробуйте вручную скомпилировать с MinGW (т.е. через консоль, просто перейти в директорию где лежат исходники и ввести `g++ main.cpp -std=c++17`.
Либо попробуйте удалить `constexpr` у функции `constexpr auto generate...`.

**Comment by Stinger1000** [comment]
![image](https://user-images.githubusercontent.com/56435313/75113148-31c20400-565c-11ea-940c-af632a32e5e0.png)
Не знаю, это странно, как будто кодировка другая, а можно все таки пользоваться Visual Studio, 19 года версия стала работать несколько быстрее и как-то интерфейс больше нравится.

**Comment by GOOD-Stuff** [comment]
Возможно стоит просто убрать все упоминания `constexpr`. Не похоже на проблему с кодировкой. Вы можете использовать любую IDE.

**Comment by GOOD-Stuff** [comment]
В случае, если у вас больше нет вопросов и всё понятно, закрывайте *Issue* самостоятельно.
