### ISSUE TITLE
Перегрузка оператора потокового вывода

### ISSUE THREAD

**Issue by Stinger1000** [GOOD-Stuff/ssw_lab_4sem#24]
Возникает ошибка при перегрузке(не видит)
![image](https://user-images.githubusercontent.com/56435313/76448575-9c549d00-63db-11ea-822d-79785adc0e83.png)
![image](https://user-images.githubusercontent.com/56435313/76448625-b1313080-63db-11ea-93f2-d533b4609746.png)

**Comment by GOOD-Stuff** [comment]
А как выглядит тело класса `list_simply<T>`? 
[Дело в том](https://isocpp.org/wiki/faq/templates#template-friends), что компилятор не знает, что перегрузка оператора извлечения (`<<`) должна быть шаблонной (т.к. ваш класс шаблон). 
Соответственно у вас два варианта: первый - определить перегрузку раньше, чем вы объявите её в теле класса; второй - реализацию перегрузки оператора сделать сразу же в теле класса (при объявлении).
1 вариант:
```C++
// MyListClass.h
template <class T>
class MyListClass; // объявляем о нашем классе, дабы перегрузка знала о нём

template <class T>
std::ostream& operator<< (std::ostream& out, const MyListClass<T>& obj) {
  out << "Ok";
  return out;
}

template <class T>
class MyListClass {
  // ....
  // <> после << необходим компилятору дабы указать на шаблонность. It's a magic.
  friend std::ostream& operator<< <> (std::ostream& out, const MyListClass<T> obj);
};
```
2 вариант:
```C++
// MyListClass.h

template <class T>
class MyListClass {
  // ....
  // в таком случае <> после << не нужен
  friend std::ostream& operator<<  (std::ostream& out, const MyListClass<T> obj) {
    out << "And it's too Ok";
    return out;
  }
};
```
