### ISSUE TITLE
Количество лабораторных к выполнению

### ISSUE THREAD

**Issue by michael2024-lw** [GOOD-Stuff/ssw_lab_4sem#33]
Здравствуйте, нужно выполнить все 4 лабораторные работы, или же, только двух достаточно?

**Comment by GOOD-Stuff** [comment]
Добрый день.
В идеале 4, но очевидно если все сейчас мне начнут кидать запросы с 4мя лабами, то я их не успею проверить до начала сессии. 
По хорошему вы должны были присылать реквесты по ходу выполнения лаб, т.е. выполнили 1ую -> скинули, пока ждёте результатов -> делаете следующую и т.д.

**Comment by michael2024-lw** [comment]
А если сделать 4, то баллы к экзамену будут выше?

**Comment by GOOD-Stuff** [comment]
Если я их успею проверить, тогда да.
