### ISSUE TITLE
Дедлайн сдачи лабораторных

### ISSUE THREAD

**Issue by Overfirst** [GOOD-Stuff/ssw_lab_4sem#39]
Сегодня поступила информация, что теперь дедлайн сдачи всех работ - пятница на этой неделе, грубо говоря 00:00 суббота. За это время нереально успеть сделать и отладить все лабы. Было ещё сказано, что проверять вы их будете в выходные.

Так может дадите ещё хотя бы денёк на то чтобы всё успеть? Даже при таком распределении очень маловероятно, что мы успеем сделать хотя бы одну из оставшихся. Проблемы, определённо, наши, но если всё-таки есть какой-то шанс продлить сроки, было бы здорово. Лабы сложные - не думаю, что за этот день прилетит намного больше запросов, чем обычно.

**Comment by GOOD-Stuff** [comment]
> Так может дадите ещё хотя бы денёк 

могу дать время до воскресенья (т.е. в воскресенье я уже буду проверять и больше никаких лаб не приму), но там уже буду выставлять сразу, без права на внесения правок.
