### ISSUE TITLE
Questions. Lab_1

### ISSUE THREAD

**Issue by Stinger1000** [GOOD-Stuff/ssw_lab_4sem#5]
1.How to combine a method and an operator? Example: 'name_class'.an(3) = 5;
2. How should operators <> work? I made an empty structure as type < there is data in the structure.

**Comment by GOOD-Stuff** [comment]
1. Не совсем понимаю вопрос, `an(int indx)` является методом, а не оператором. Чтобы использовать метод в том варианте, в котором предлагаете вы, он (метод) должен возвращать ссылку на элемент. 
Т.е. что-то в стиле `int& MyStruct::at(int index) { return inner_array[index]; }`
2. Что вы подразумеваете под оператором `<>`? Оператор сравнения `<` и `>`? Или уточнение типа шаблона `<some type>`? 

P.S. Вопросы на самом деле не обязательно задавать на английском (:

**Comment by Stinger1000** [comment]
1. Перепутал метод. У вектора есть метод произвольного доступа к элементу : 
vector.at(4)=7 //изменили значение 4 элемента на 7. Я не понимаю как можно сделать так чтобы с методом был оператор присваивания. 
2. Да, операторы сравнения. я сравниваю две структуры данных как написал выше, пустая структура больше чем структура с элементами.

**Comment by GOOD-Stuff** [comment]
1. Я уже написал как, прочтите внимательнее, либо загуглите *return reference value* (: 
2. Лексикографическое сравнение подразумевает сравнение поэлементно, при этом если элементы не равны друг другу (т.е. происходит неравенство), то сравнение прекращается и возвращается результат этого сравнения. 
Например (псевдокод):
```C++
// у нас есть две структуры 
struct_t test1 { 0, 1, 5 };
struct_t test2 { 0, 5, 1 };

// производим лексикографическое сравнение test1 < test2
operator < (const struct_t& test1, const struct_t& test2) {
    auto* ptrL = lh.arr;
    auto* ptrR = rh.arr;
		
    do {
        cout << "Here: " << *ptrL << " < " << *ptrR << endl;
    // разыменовываем указатели, сравниваем их "содержимое"
    // и затем инкрементируем указатели (адреса), т.е. переходим к 
    // следующим элементам массивов
	if (*ptrL++ == *ptrR++) 
	    continue;
			
	return (*ptrL < *ptrR);
    } while (ptrL != nullptr && ptrR != nullptr); // обязываем проверять оба условия

    // если вдруг элементы в структурах равны, но кол-во их различается
    if (lh.count() > rh.count()) return false;
    if (lh.count() < rh.count()) return false;
		
   return false;
}
```

**Comment by GOOD-Stuff** [comment]
UPD: или как вариант использовать [std::lexicographical_compare](https://docs.w3cub.com/cpp/algorithm/lexicographical_compare/) "под капотом" своих сравнений.
